### ISSUE TITLE
Quickstart fails with "Unknown layer: MaxoutDense"

### ISSUE THREAD

**Issue by nerikosans** [Letuvertia/Violin-Body-Movement-Generation#1]
Hi, I'm interested in your work, and want to reproduce your results.
However, running `python skeletonGeneration_Main.py` with initial config (no change after cloning) fails here:
```
File "skeletonGeneration_Main.py", line 78, in <module>
    arousal = md2.getArousalAnnotation(inputMusic_loc)
  File "/data/unagi0/mine/src/Violin-Body-Movement-Generation/skeletonGeneration_Functions.py", line 185, in getArousalAnnotation
    model = load_model('./arousalNetwork_model.h5')
```
with the following error message.
```
ValueError: Unknown layer: MaxoutDense
```

Please kindly let me know about possible cause of this error.
This might be due to version incompatibility, so could you publish `requirements.txt`?

<details><summary>Full log</summary>
<p>

```
=======GET CHANGING POINTS(THRESHOLD)=======
Predicting Potential Changing Points of testingTrackforQuickStart
2020-10-22 11:12:17.709083: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-10-22 11:12:17.725717: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2400180000 Hz
2020-10-22 11:12:17.728038: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5620c5a23390 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-22 11:12:17.728087: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-22 11:12:17.728302: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Output Label Length : 1816 frames
Delay for 32 frames, start at the 33th frame
Warning: stereo wav file. Converting it to mono for the analysis.
=======GET FINGER ARRANGEMENTS=======
Output Finger Arrangements : 1879 frames
=======WRITING NOTES INTO MIDI FILE=======
save in name of : testingTrackforQuickStart_MIDI.mid
=======GET AROUSAL ANNOTATIONS=======
Predicting Arousal Annotations of testingTrackforQuickStart
Traceback (most recent call last):
  File "skeletonGeneration_Main.py", line 78, in <module>
    arousal = md2.getArousalAnnotation(inputMusic_loc)
  File "/data/unagi0/mine/src/Violin-Body-Movement-Generation/skeletonGeneration_Functions.py", line 185, in getArousalAnnotation
    model = load_model('./arousalNetwork_model.h5')
  File "/home/mil/mine/.pyenv/versions/anaconda3-2019.03/envs/violin/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 184, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/mil/mine/.pyenv/versions/anaconda3-2019.03/envs/violin/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 178, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/home/mil/mine/.pyenv/versions/anaconda3-2019.03/envs/violin/lib/python3.7/site-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/mil/mine/.pyenv/versions/anaconda3-2019.03/envs/violin/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 109, in deserialize
    printable_module_name='layer')
  File "/home/mil/mine/.pyenv/versions/anaconda3-2019.03/envs/violin/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 373, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/mil/mine/.pyenv/versions/anaconda3-2019.03/envs/violin/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 398, in from_config
    custom_objects=custom_objects)
  File "/home/mil/mine/.pyenv/versions/anaconda3-2019.03/envs/violin/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 109, in deserialize
    printable_module_name='layer')
  File "/home/mil/mine/.pyenv/versions/anaconda3-2019.03/envs/violin/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 373, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/mil/mine/.pyenv/versions/anaconda3-2019.03/envs/violin/lib/python3.7/site-packages/tensorflow/python/keras/layers/wrappers.py", line 85, in from_config
    config.pop('layer'), custom_objects=custom_objects)
  File "/home/mil/mine/.pyenv/versions/anaconda3-2019.03/envs/violin/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 109, in deserialize
    printable_module_name='layer')
  File "/home/mil/mine/.pyenv/versions/anaconda3-2019.03/envs/violin/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 362, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/home/mil/mine/.pyenv/versions/anaconda3-2019.03/envs/violin/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 321, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: MaxoutDense
```

</p>
</details>

<details><summary>Package versions</summary>
<p>

```
Package                Version
---------------------- ----------------------------
absl-py                0.10.0
AMFM-decompy           1.0.10
appdirs                1.4.4
astor                  0.8.1
astunparse             1.6.3
audioread              2.1.9
blinker                1.4
brotlipy               0.7.0
cachetools             4.1.1
certifi                2020.6.20
cffi                   1.14.3
chardet                3.0.4
click                  7.1.2
cryptography           3.1.1
Cython                 0.29.21
decorator              4.4.2
gast                   0.3.3
google-auth            1.21.3
google-auth-oauthlib   0.4.1
google-pasta           0.2.0
grpcio                 1.31.0
h5py                   2.10.0
idna                   2.10
importlib-metadata     2.0.0
joblib                 0.17.0
Keras                  2.4.3
Keras-Preprocessing    1.1.0
librosa                0.8.0
llvmlite               0.34.0
madmom                 0.16.1
Markdown               3.3.2
MIDIUtil               1.2.1
mido                   1.2.9
nltk                   3.4.5
numba                  0.51.2
numpy                  1.19.2
oauthlib               3.0.1
opt-einsum             0+untagged.61.gd905544.dirty
packaging              20.4
pip                    20.2.4
pooch                  1.2.0
protobuf               3.13.0
pyasn1                 0.4.8
pyasn1-modules         0.2.7
pycparser              2.20
PyJWT                  1.7.1
pyOpenSSL              19.1.0
pyparsing              2.4.7
PySocks                1.7.1
PyYAML                 5.3.1
requests               2.24.0
requests-oauthlib      1.3.0
resampy                0.2.2
rsa                    4.6
scikit-learn           0.23.2
scipy                  1.5.2
setuptools             49.6.0.post20201009
six                    1.15.0
SoundFile              0.10.3.post1
tensorboard            2.3.0
tensorboard-plugin-wit 1.6.0.post3
tensorflow             2.2.0
tensorflow-estimator   2.2.0
termcolor              1.1.0
threadpoolctl          2.1.0
urllib3                1.25.11
Werkzeug               1.0.1
wheel                  0.35.1
wrapt                  1.12.1
zipp                   3.3.1
```

</p>
</details>

**Comment by nerikosans** [comment]
@Letuvertia 
Mr. Liu, could you take a look on this issue?
I guess the problem is version incompatibility of pip packages.
Please kindly consider uploading `requirements.txt` .
